### ISSUE TITLE
🌟 Create more options menu modal 

### ISSUE THREAD

**Issue by calebjanhunen** [calebjanhunen/fitracker-app#13]
## Summary
**Describe the solution you'd like**
- Create a menu when the kebab icon is clicked
- Use Bottom Sheet Modal

## Tasks

- [ ] Import bottom sheet modal and set up basic component
- [ ] Display at root of app (over navigation bar)
- [ ] Create Bottom sheet component and make it reusable
