### ISSUE TITLE
🌟 Create Start Workout Page

### ISSUE THREAD

**Issue by calebjanhunen** [calebjanhunen/fitracker-app#5]
**Is your feature request related to a problem? Please describe.**
- Need page to start workout (from template or empty)

**Describe the solution you'd like**
- This page will display once user clicks start workout on workout tracker main page  (#4)
- Page will contain a list of templates and ability to create a workout template
- Will contain a button to start workout

**Tasks**
- [ ] Create list for workout templates
- [ ] Create workout template component
- [ ] Add button to create template
- [ ] Add button to start workout

**Additional context**
[Workout Tracker Feature - Figma](https://www.figma.com/file/WXXWHua9eqaAsTh3PfXmr5/FitFriends---Workout-Tracker-Feature?type=design&node-id=0-1&mode=design&t=24c4RVyveIBjNbjc-0)
