### ISSUE TITLE
🌟 Create Workout Tracker Modal (When Start workout is pressed)

### ISSUE THREAD

**Issue by calebjanhunen** [calebjanhunen/fitracker-app#7]
## Summary
**Describe the solution you'd like**
- When `Start Empty Workout` or `Start Workout ('template')` is pressed on the `Start Workout` page the workout modal will appear (bottom sheet modal)
- Will have the ability to add exercises and add sets to exercises

## Tasks

- [ ] Hook up buttons to open workout modal
- [ ] Create workout modal with ability to drag it down to bottom to navigate app
- [ ] Create exercise template
- [ ] Add `Add Exercise` button
- [ ] Add Finish and cancel workout buttons
- [ ] On finish workout show modal window asking if user would like to share workout

## More Info
**Additional context**
[Workout Tracker Feature - Figma](https://www.figma.com/file/WXXWHua9eqaAsTh3PfXmr5/FitFriends---Workout-Tracker-Feature?type=design&node-id=0-1&mode=design&t=8sAFNHU9EVMUwlrD-0)
