### ISSUE TITLE
🌟 Create Add Exercise Modal

### ISSUE THREAD

**Issue by calebjanhunen** [calebjanhunen/fitracker-app#8]
## Summary
**Describe the solution you'd like**
- When user presses `Add Exercise` a modal window will show up with exercises and an ability to add exercises to the workout

## Tasks
- [ ] Create Add Exercise Modal
- [ ] Hook up `Add Exercise` button to open modal
- [ ] Create exercise component

## More Info
[Workout Tracker Feature - Figma](https://www.figma.com/file/WXXWHua9eqaAsTh3PfXmr5/FitFriends---Workout-Tracker-Feature?type=design&node-id=0-1&mode=design&t=8sAFNHU9EVMUwlrD-0)
